//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class frmPrincipal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmPrincipal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Custo.frmPrincipal", typeof(frmPrincipal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=50, Height=20}.
        /// </summary>
        public static System.Drawing.Size ajudaToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("ajudaToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajuda.
        /// </summary>
        public static string ajudaToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("ajudaToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=50, Height=20}.
        /// </summary>
        public static System.Drawing.Size ajudaToolStripMenuItem1_Size {
            get {
                object obj = ResourceManager.GetObject("ajudaToolStripMenuItem1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajuda.
        /// </summary>
        public static string ajudaToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("ajudaToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool barraStatus_AutoSize {
            get {
                object obj = ResourceManager.GetObject("barraStatus.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=608}.
        /// </summary>
        public static System.Drawing.Point barraStatus_Location {
            get {
                object obj = ResourceManager.GetObject("barraStatus.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=983, Height=22}.
        /// </summary>
        public static System.Drawing.Size barraStatus_Size {
            get {
                object obj = ResourceManager.GetObject("barraStatus.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int barraStatus_TabIndex {
            get {
                object obj = ResourceManager.GetObject("barraStatus.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statusStrip1.
        /// </summary>
        public static string barraStatus_Text {
            get {
                return ResourceManager.GetString("barraStatus.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=132,Y=17}.
        /// </summary>
        public static System.Drawing.Point barraStatus_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("barraStatus.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles btnSair_Anchor {
            get {
                object obj = ResourceManager.GetObject("btnSair.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleLeft.
        /// </summary>
        public static System.Drawing.ContentAlignment btnSair_ImageAlign {
            get {
                object obj = ResourceManager.GetObject("btnSair.ImageAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=908,Y=607}.
        /// </summary>
        public static System.Drawing.Point btnSair_Location {
            get {
                object obj = ResourceManager.GetObject("btnSair.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size btnSair_Size {
            get {
                object obj = ResourceManager.GetObject("btnSair.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        public static int btnSair_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnSair.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string btnSair_Text {
            get {
                return ResourceManager.GetString("btnSair.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=182, Height=22}.
        /// </summary>
        public static System.Drawing.Size cadastroDeClientestoosst_Size {
            get {
                object obj = ResourceManager.GetObject("cadastroDeClientestoosst.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Clientes.
        /// </summary>
        public static string cadastroDeClientestoosst_Text {
            get {
                return ResourceManager.GetString("cadastroDeClientestoosst.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=130, Height=20}.
        /// </summary>
        public static System.Drawing.Size cadastroDeUsuariosToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("cadastroDeUsuariosToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Usuarios.
        /// </summary>
        public static string cadastroDeUsuariosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("cadastroDeUsuariosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool cadastroDeUsuariosToolStripMenuItem_Visible {
            get {
                object obj = ResourceManager.GetObject("cadastroDeUsuariosToolStripMenuItem.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=130, Height=20}.
        /// </summary>
        public static System.Drawing.Size cadastroDeUsuariosToolStripMenuItem1_Size {
            get {
                object obj = ResourceManager.GetObject("cadastroDeUsuariosToolStripMenuItem1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Usuarios.
        /// </summary>
        public static string cadastroDeUsuariosToolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("cadastroDeUsuariosToolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=61, Height=20}.
        /// </summary>
        public static System.Drawing.Size cadastrosToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("cadastrosToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string cadastrosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("cadastrosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=182, Height=22}.
        /// </summary>
        public static System.Drawing.Size clientesToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("clientesToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Clientes.
        /// </summary>
        public static string clientesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("clientesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=141, Height=22}.
        /// </summary>
        public static System.Drawing.Size composiçãoToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("composiçãoToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composição.
        /// </summary>
        public static string composiçãoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("composiçãoToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=54, Height=20}.
        /// </summary>
        public static System.Drawing.Size lucrosToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("lucrosToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucros.
        /// </summary>
        public static string lucrosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("lucrosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=49, Height=20}.
        /// </summary>
        public static System.Drawing.Size lucroToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("lucroToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucro.
        /// </summary>
        public static string lucroToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("lucroToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point menuStrip1_Location {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=983, Height=24}.
        /// </summary>
        public static System.Drawing.Size menuStrip1_Size {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int menuStrip1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menuStrip1.
        /// </summary>
        public static string menuStrip1_Text {
            get {
                return ResourceManager.GetString("menuStrip1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point menuStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=182, Height=22}.
        /// </summary>
        public static System.Drawing.Size pedidosToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("pedidosToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedidos.
        /// </summary>
        public static string pedidosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("pedidosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=141, Height=22}.
        /// </summary>
        public static System.Drawing.Size produtosToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("produtosToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        public static string produtosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("produtosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=62, Height=20}.
        /// </summary>
        public static System.Drawing.Size produtoToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("produtoToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto.
        /// </summary>
        public static string produtoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("produtoToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=245,Y=17}.
        /// </summary>
        public static System.Drawing.Point timer1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=61, Height=20}.
        /// </summary>
        public static System.Drawing.Size toolStripMenuItem1_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripMenuItem1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string toolStripMenuItem1_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=182, Height=22}.
        /// </summary>
        public static System.Drawing.Size toolStripMenuItem3_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripMenuItem3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedidos.
        /// </summary>
        public static string toolStripMenuItem3_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=62, Height=20}.
        /// </summary>
        public static System.Drawing.Size toolStripMenuItem4_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripMenuItem4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto.
        /// </summary>
        public static string toolStripMenuItem4_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=141, Height=22}.
        /// </summary>
        public static System.Drawing.Size toolStripMenuItem5_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripMenuItem5.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        public static string toolStripMenuItem5_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=141, Height=22}.
        /// </summary>
        public static System.Drawing.Size toolStripMenuItem6_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripMenuItem6.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composição.
        /// </summary>
        public static string toolStripMenuItem6_Text {
            get {
                return ResourceManager.GetString("toolStripMenuItem6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=210, Height=17}.
        /// </summary>
        public static System.Drawing.Size tsData_Size {
            get {
                object obj = ResourceManager.GetObject("tsData.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data: .
        /// </summary>
        public static string tsData_Text {
            get {
                return ResourceManager.GetString("tsData.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleRight.
        /// </summary>
        public static System.Drawing.ContentAlignment tsData_TextAlign {
            get {
                object obj = ResourceManager.GetObject("tsData.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=210, Height=17}.
        /// </summary>
        public static System.Drawing.Size tsHorario_Size {
            get {
                object obj = ResourceManager.GetObject("tsHorario.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario:.
        /// </summary>
        public static string tsHorario_Text {
            get {
                return ResourceManager.GetString("tsHorario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleRight.
        /// </summary>
        public static System.Drawing.ContentAlignment tsHorario_TextAlign {
            get {
                object obj = ResourceManager.GetObject("tsHorario.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=50, Height=17}.
        /// </summary>
        public static System.Drawing.Size tsUsuario_Size {
            get {
                object obj = ResourceManager.GetObject("tsUsuario.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario:.
        /// </summary>
        public static string tsUsuario_Text {
            get {
                return ResourceManager.GetString("tsUsuario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=210, Height=17}.
        /// </summary>
        public static System.Drawing.Size txtData_Size {
            get {
                object obj = ResourceManager.GetObject("txtData.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.
        /// </summary>
        public static string txtData_Text {
            get {
                return ResourceManager.GetString("txtData.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleLeft.
        /// </summary>
        public static System.Drawing.ContentAlignment txtData_TextAlign {
            get {
                object obj = ResourceManager.GetObject("txtData.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.RightToLeft similar to No.
        /// </summary>
        public static System.Windows.Forms.RightToLeft txtHora_RightToLeft {
            get {
                object obj = ResourceManager.GetObject("txtHora.RightToLeft", resourceCulture);
                return ((System.Windows.Forms.RightToLeft)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=210, Height=17}.
        /// </summary>
        public static System.Drawing.Size txtHora_Size {
            get {
                object obj = ResourceManager.GetObject("txtHora.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hora.
        /// </summary>
        public static string txtHora_Text {
            get {
                return ResourceManager.GetString("txtHora.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleLeft.
        /// </summary>
        public static System.Drawing.ContentAlignment txtHora_TextAlign {
            get {
                object obj = ResourceManager.GetObject("txtHora.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=78, Height=17}.
        /// </summary>
        public static System.Drawing.Size txtUsuario_Size {
            get {
                object obj = ResourceManager.GetObject("txtUsuario.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nomeUsuario.
        /// </summary>
        public static string txtUsuario_Text {
            get {
                return ResourceManager.GetString("txtUsuario.Text", resourceCulture);
            }
        }
    }
}
